name: ec2 Workflow

on:
  push:

jobs:
  stage_build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
      - name: Lauching the production ec2
        run: |
          sudo apt-get install git -y
          git clone https://github.com/AbhijeetJy/ops_prac.git
          python -m pip install --upgrade pip
          # pip3 install -r /ops_prac/webapp/require.txt this is not required as docker image has this
          sudo apt-get install docker -y
          sudo systemctl start docker
          sudo chmod 777 /var/run/docker.sock
          cd ops_prac
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=ap-south-1
          docker build -f flaskimage.dockerfile -t tryimage .
          mkdir ./key
          aws s3 cp s3://adminbucket-nj-abhi-123/keys/TEC2.pem ./key/
          sudo chmod 0400 ./key/TEC2.pem
          pwd
          ls -l ./key/TEC2.pem
          ls
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r3o8w1g0
          docker tag tryimage:latest public.ecr.aws/r3o8w1g0/test-flask:latest
          docker push public.ecr.aws/r3o8w1g0/test-flask:latest
      # - name: Add EC2 host key to known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H ec2-13-234-21-13.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts
      # - name: Running the file to target ec2
      #   run: |
      #     ls /home/runner/work/ops_prac/ops_prac/ops_prac/key
      #     ls /home/runner/work/ops_prac/ops_prac/ops_prac
      #     # scp -i /home/runner/work/ops_prac/ops_prac/ops_prac/key/TEC2.pem /home/runner/work/ops_prac/ops_prac/ops_prac/yaytec2.sh ec2-13-234-21-13.ap-south-1.compute.amazonaws.com:/home/ec2-user/
      #     # ssh -i ./key/TEC2.pem ec2-13-234-21-13.ap-south-1.compute.amazonaws.com
      #     ssh -i /home/runner/work/ops_prac/ops_prac/ops_prac/key/TEC2.pem ec2-user@13.234.21.13
      - name: Upload file to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no /home/runner/work/ops_prac/ops_prac/ops_prac/yaytec2.sh ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/
      - name: Set execute permissions on script
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "chmod +x /home/ec2-user/yaytec2.sh"
      - name: SSH into EC2 instance and run commands
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            echo "Connected to EC2 instance successfully!"
            # Run your script or commands here
            echo "Running script..."
            /home/ec2-user/yaytec2.sh
            # Or run inline commands
            echo "Listing files..."
            ls -la
          EOF
