name: ec2 Workflow

on:
  push:

jobs:
  stage_build:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Lauching the production ec2
        run: |
          yes | sudo yum install git
          pip install -r requirements.txt
          sudo yum install docker -y
          sudo systemctl start docker
          sudo chmod 777 /var/run/docker.sock
          cd ops_prac
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=ap-south-1
          docker build -f flaskimage.dockerfile -t tryimage .
          mkdir ./key
          aws s3 cp s3://adminbucket-nj-abhi-123/keys/TEC2.pem ./key/
          sudo chmod 400 ./key/TEC2.pem
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r3o8w1g0
          docker tag tryimage:latest public.ecr.aws/r3o8w1g0/test-flask:latest
          docker push public.ecr.aws/r3o8w1g0/test-flask:latest
          
